name: Coletar Dados Completos de Contribuição

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  construir:
    runs-on: ubuntu-latest
    name: Gerar arquivo de dados de contribuição
    steps:
      - uses: actions/checkout@v3

      - name: Gerar arquivo de dados a partir do histórico completo
        uses: Platane/snk/svg-only@v3
        with:
          # usuário diretamente aqui.
          github_user_name: 'messias-code'
          outputs: |
            dist/contribution-data.csv?from=all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checar se o arquivo de saída existe
        id: checar_arquivo
        run: |
          if [ -f "dist/contribution-data.csv" ]; then
            echo "Arquivo de contribuição encontrado. Prosseguindo com o envio."
            echo "existe=true" >> $GITHUB_OUTPUT
          else
            echo "AVISO: Nenhum arquivo de contribuição foi gerado. Pulando o passo de envio."
            echo "existe=false" >> $GITHUB_OUTPUT
          fi

      - name: Enviar arquivo de dados para o branch de saída
        if: steps.checar_arquivo.outputs.existe == 'true'
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
